# Generated by Django 4.0.1 on 2022-03-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.TextField()),
                ('mobilenumber', models.BigIntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('farmer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_no', models.BigIntegerField()),
                ('farmer_name', models.TextField(max_length=40)),
                ('place', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='plant',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=60)),
                ('type_of_plant', models.TextField(max_length=30)),
                ('price', models.IntegerField()),
                ('soil_type', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='seeds',
            fields=[
                ('seed_name', models.TextField(max_length=100)),
                ('seed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('soil_type', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='seed_purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.farmer')),
                ('seed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.seeds')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('product_botname', models.TextField(null=True)),
                ('product_type', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('soil_type', models.TextField()),
                ('product_image', models.ImageField(upload_to='hello/static/images')),
                ('Order', models.ManyToManyField(to='hello.plant')),
            ],
        ),
        migrations.CreateModel(
            name='plant_purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.farmer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('email_id', models.EmailField(blank=True, max_length=100)),
                ('customer_name', models.TextField(max_length=30)),
                ('phone_no', models.BigIntegerField()),
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Order', models.ManyToManyField(to='hello.plant')),
            ],
        ),
    ]
