# Generated by Django 4.0.1 on 2022-03-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Order',
            new_name='order',
        ),
    ]
