# Generated by Django 4.0.1 on 2022-03-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_products_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emailid',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='usrname',
            new_name='username',
        ),
    ]
