# Generated by Django 4.0.1 on 2022-03-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_rename_emailid_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='emailid',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='usrname',
        ),
    ]
