# Generated by Django 4.0.1 on 2022-03-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_rename_email_customer_emailid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='order',
            new_name='orders',
        ),
    ]
