# Generated by Django 4.0.1 on 2022-03-24 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_rename_order_products_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emailid',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='usrname',
            new_name='username',
        ),
    ]
