# Generated by Django 4.0.1 on 2022-03-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='id',
            new_name='product_id',
        ),
    ]
