# Generated by Django 4.0.1 on 2022-03-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_rename_id_products_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.TextField(),
        ),
    ]
