# Generated by Django 4.0.1 on 2022-03-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_rename_username_order_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customername',
            field=models.TextField(null=True),
        ),
    ]
